### ISSUE TITLE
module.js:337

### ISSUE THREAD

**Issue by sononix** [node-js-libs/node.io#115]
Running one of the examples 

<code>
var nodeio = require('node.io');
exports.job = new nodeio.Job({
    input: [0,1,2],
    run: function (num) {
        this.emit(num \* 2);
    }
});

</code>

but getting error
<code>
module.js:337
    throw new Error("Cannot find module '" + request + "'");
          ^
Error: Cannot find module '../../vendor/validator'
    at Function._resolveFilename (module.js:337:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Object.<anonymous> (/Users/ms/.nvm/v0.6.20/lib/node_modules/node.io/lib/node.io/job.js:7:17)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Module.require (module.js:359:17)
</code>

what might I be missing 

tks
M

**Comment by chriso** [comment]
It looks like node.io didn't install properly, try reinstalling with `npm install node.io`.
