### ISSUE TITLE
why “save” example not worked for me 

### ISSUE THREAD

**Issue by singleseeker** [node-js-libs/node.io#132]
i copy the code like wiki said,saved it on my desktop. and run it .
but ...

seeker at seekermatoMacBook-Pro in ~/Desktop
$ node.io --debug save.js
DEBUG: Attempting to load require('/Users/seeker/Desktop/save.js')
ERROR: Error: Failed to load job "save.js". Please check that the job exists and compiles correctly.

/usr/local/lib/node_modules/node.io/lib/node.io/processor.js:314
                        throw e;
                              ^
Error: Cannot find module 'node.io'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Users/seeker/Desktop/save.js:1:76)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)

this is not the right way to run code?

**Comment by singleseeker** [comment]
sorry,i just install node.js used -g ,this is a wrong way,if i wanna to require "node.io",i should also,npm install node.io locally
