### ISSUE TITLE
Unknown method 'tick' for utils object

### ISSUE THREAD

**Issue by harrisj** [node-js-libs/node.io#141]
I installed node.io using this command

  npm install -g node.io

And the version is v0.4.13. When I attempt to run the hello.coffee example, I get this error though

/usr/local/share/npm/lib/node_modules/node.io/lib/node.io/process_worker.js:86
      utils.tick(function () {
             ^
 TypeError: Object #<Object> has no method 'tick'
      at EventEmitter.<anonymous> (/usr/local/share/npm/lib/node_modules/node.io/lib/node.io/process_worker.js:86:15)
    at EventEmitter.emit (events.js:93:17)
    at EventEmitter.Processor.setupWorkerEvents.worker.on.utils.tick.job.ready_to_request_input (/usr/local/share/npm/lib/node_modules/node.io/lib/node.io/process_worker.js:77:20)
    at EventEmitter.emit (events.js:96:17)
    at EventEmitter.<anonymous> (/usr/local/share/npm/lib/node_modules/node.io/lib/node.io/process_master.js:202:24)
    at EventEmitter.emit (events.js:99:17)
    at master.on.handle_input (/usr/local/share/npm/lib/node_modules/node.io/lib/node.io/process_master.js:118:24)
    at EventEmitter.<anonymous> (/usr/local/share/npm/lib/node_modules/node.io/lib/node.io/process_master.js:157:17)
    at EventEmitter.emit (events.js:93:17)
    at EventEmitter.<anonymous> (/usr/local/share/npm/lib/node_modules/node.io/lib/node.io/process_master.js:95:16)

**Comment by chriso** [comment]
You updated the global node.io but probably didn't update the local copy that your script uses when you `require('node.io')`.

Try running `npm install node.io` in the same directory as your `hello.coffee`.

The following command should output **node.io@0.4.13** twice

``` bash
$ ( npm ls -gs && npm ls -s ) | grep node.io
```

**Comment by harrisj** [comment]
Oof. That was it! Sorry, but thanks for the prompt reply.

On Mar 18, 2013, at 6:45 PM, "chriso" <notifications@github.com<mailto:notifications@github.com>> wrote:

You updated the global node.io but probably didn't update the local copy that your script uses when you require('node.io').

Try running npm install node.io in the same directory as your hello.coffee.

Both of the following commands should output node.io@0.4.13mailto:node.io@0.4.13

$ npm ls -g 2>/dev/null | grep node.io
$ npm ls 2>/dev/null | grep node.io
