### ISSUE TITLE
Broken for 0.3.7

### ISSUE THREAD

**Issue by jlfwong** [node-js-libs/node.io#15]
This happens on every request (something to do with how destroy has changed/moved around)

Also, createClient has been removed from the public API docs

   http.js:330
      this.socket.destroy(error);
                  ^
    TypeError: Cannot call method 'destroy' of null
        at ClientRequest.destroy (http.js:330:15)
        at /usr/local/lib/node/.npm/node.io/0.2.1-18/package/lib/node.io/request.js:225:25
        at IncomingMessage.<anonymous> (/usr/local/lib/node/.npm/node.io/0.2.1-18/package/lib/node.io/request.js:321:13)
        at IncomingMessage.emit (events.js:59:20)
        at HTTPParser.onMessageComplete (http.js:111:23)
        at Client.onData [as ondata](http.js:1227:27)
        at Client._onReadable (net.js:623:27)
        at IOWatcher.onReadable [as callback](net.js:156:10)

**Comment by chriso** [comment]
Hi, this was fixed recently - run `npm update` to get the latest version of node.io

createClient hasn't been removed from the stable (0.2.x) API. It's being phased out in 0.3.x and will be fully deprecated by 0.4.x - in order to keep node.io working for the majority, I'll keep using createClient until the 0.3.x branch is stable. I'll also include the new `require('https')` interface - all of this should be soon.
