### ISSUE TITLE
Cant get Reddit example to work for any other page

### ISSUE THREAD

**Issue by jdsiddon** [node-js-libs/node.io#151]
I have tried to change the url for the reddit example you have provided along with altering my selectors.  I cant seem to get the code to work for anything.  Using -g for the debugger simply gives me "ERROR: Error: Failed to load job "

Here is my Code:
var nodeio = require('node.io');
var methods = {
    input: false,
    run: function() {
        this.getHtml('http://www.gunbroker.com/', function(err, $) {

```
        //Handle any request / parsing errors
        if (err) this.exit(err);

        var titles = [], output = [];

        //Select all titles on the page
        $('div').each(function(a) {
            titles.push(a.text); 
        });


        for (var i = 0, len = titles.length; i < len; i++) {
            //Output = [score] title
            output.push(titles[i]);
        }

        this.emit(output);
    });
}
```

}

exports.job = new nodeio.Job({timeout:10}, methods);

Here is the error:

bob:crawler justin$ node.io -g gunbroker
ERROR: Error: Failed to load job "gunbroker". Please check that the job exists and compiles correctly.

/usr/local/lib/node_modules/node.io/lib/node.io/processor.js:315
                        throw e;
                              ^
TypeError: Object #<Object> has no method 'debug'
    at status (/usr/local/lib/node_modules/node.io/lib/node.io/utils.js:47:17)
    at Object.forEach.exports.status.(anonymous function) [as debug](/usr/local/lib/node_modules/node.io/lib/node.io/utils.js:55:9)
    at Processor.status (/usr/local/lib/node_modules/node.io/lib/node.io/processor.js:469:37)
    at Processor.loadJob (/usr/local/lib/node_modules/node.io/lib/node.io/processor.js:307:26)
    at Object.exports.start (/usr/local/lib/node_modules/node.io/lib/node.io/processor.js:108:15)
    at Object.exports.cli (/usr/local/lib/node_modules/node.io/lib/node.io/interfaces/cli.js:152:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/node.io/bin/node.io:5:14)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)

I have tried reinstalling node.io a number of times globally and in the specific file.  I am running node v 0.8.19.  Any ideas whats up?  Thank you!

**Comment by chriso** [comment]
It was a bug introduced in 2d1a631769830cd148c38f27dbad13fc4614b077 and fixed in cddcb095bc2a32268e90b4b9add70be7674efd77. The latest version `0.5.1` includes the fix
