### ISSUE TITLE
TypeError: Object #<Hello> has no method 'extend'

### ISSUE THREAD

**Issue by srid** [node-js-libs/node.io#17]
node 0.4 on OSX using the hello.coffee example in wiki.

```
$ node.io-web -p 8080 .node_modules
INFO: Listening on port 8080

Running job "hello.coffee"

/Users/sridharr/.nvm/v0.4.0/lib/node/.npm/node.io/0.2.2-5/package/lib/node.io/processor.js:113
            job_obj = job_obj.extend(options.extend.options || {}, options.ext
                              ^
TypeError: Object #<Hello> has no method 'extend'
    at /Users/sridharr/.nvm/v0.4.0/lib/node/.npm/node.io/0.2.2-5/package/lib/node.io/processor.js:113:31
    at /Users/sridharr/.nvm/v0.4.0/lib/node/.npm/node.io/0.2.2-5/package/lib/node.io/processor.js:154:13
    at /Users/sridharr/.nvm/v0.4.0/lib/node/.npm/node.io/0.2.2-5/package/lib/node.io/processor.js:319:53
```

**Comment by chriso** [comment]
Sorry for the delay in getting back to you. I can't seem to reproduce this bug: 

```
~/Documents$ node -v && coffee -v && node.io -v
   v0.4.0
   CoffeeScript version 1.0.1
   INFO: v0.2.2-5
~/Documents$ node.io -s hello.coffee
   Hello World!
~/Documents$
```

Try reinstalling node.io and its dependencies using `npm install node.io` and let me know how that goes.

**Comment by chriso** [comment]
I'm closing this issue as resolved. Let me know if you're still having trouble
