### ISSUE TITLE
node.io -f throws exception

### ISSUE THREAD

**Issue by codeinvain** [node-js-libs/node.io#22]
running multiple forks on a simple hello example  throws an exception

node.io -f 1 hello

/usr/local/lib/node/.npm/node.io/0.2.5-5/package/lib/node.io/processor.js:296
                this.status(JSON.stringify(e), 'debug');
                     ^
TypeError: Object #<Object> has no method 'status'
    at /usr/local/lib/node/.npm/node.io/0.2.5-5/package/lib/node.io/processor.js:296:22
    at [object Object].handleMasterMessage (/usr/local/lib/node/.npm/node.io/0.2.5-5/package/lib/node.io/process_worker.js:28:9)
    at EventEmitter.<anonymous> (/usr/local/lib/node/.npm/node.io/0.2.5-5/package/lib/node.io/processor.js:235:22)
    at EventEmitter.emit (events.js:42:17)
    at Socket.<anonymous> (/usr/local/lib/node/.npm/node.io/0.2.5-5/package/lib/node.io/multi_node.js:152:29)
    at Socket.emit (events.js:42:17)
    at Socket._onReadable (net.js:649:14)
    at IOWatcher.onReadable [as callback](net.js:156:10)

**Comment by estevaoam** [comment]
Same error here. :(

**Comment by chriso** [comment]
Should be working.
