### ISSUE TITLE
'htmlparser' module not found

### ISSUE THREAD

**Issue by kmiyashiro** [node-js-libs/node.io#23]
I am using npm 1.0rc8 and node 0.4.5

When I try running the following code:

```
var nodeio = require('node.io');

exports.job = new nodeio.Job({
    input: false,
    run: function() {
        var self = this;

        this.getHtml('http://google.com/', function(err, $) {
            if (err) { self.exit(err) }

            self.emit($('input'));
        })
    }
});
```

I get this error:

```
Error: Cannot find module 'htmlparser'
    at Function._resolveFilename (module.js:320:11)
    at Function._load (module.js:266:25)
    at require (module.js:348:19)
    at Object.<anonymous> (/opt/local/lib/node_modules/node.io/vendor/soupselect/lib/soupselect.js:8:16)
    at Module._compile (module.js:404:26)
    at Object..js (module.js:410:10)
    at Module.load (module.js:336:31)
    at Function._load (module.js:297:12)
    at require (module.js:348:19)
    at [object Object].$ (/opt/local/lib/node_modules/node.io/lib/node.io/dom.js:20:22)
```

**Comment by chriso** [comment]
I haven't tested node.io with the latest RC of npm, but if you're getting module errors try installing the missing modules:

```
sudo npm install htmlparser
```

I'll get the latest npm and test it over the next few days

**Comment by kmiyashiro** [comment]
Yep, that works. npm 1.0 installs everything locally in the project folder by default now, that probably has something to do with it.

**Comment by tazercat** [comment]
I just went through the online instructions for installing node.js and node.io.  I get the same error even after installing htmlparser using npm.

I'm amped about node.io, btw.  

 npm version 0.3.18
node.io version 0.2.5-6
node version 0.4.6

When run:
<pre><code>
var nodeio = require('node.io');
var options = {timeout: 10};

exports.job = new nodeio.Job(options, {
    input: ['hello', 'foobar','weather'],
    run: function (keyword) {
        var self = this, results;
        this.getHtml('http://www.google.com/search?q=' + encodeURIComponent(keyword), function (err, $) {
            results = $('#resultStats').text.toLowerCase();
            self.emit(keyword + ' has ' + results);
        });
    }
});
</pre></code>

I get:
<pre><code>
node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: Cannot find module '../../vendor/htmlparser/lib/htmlparser'
    at Function._resolveFilename (module.js:320:11)
    at Function._load (module.js:266:25)
    at require (module.js:348:19)
    at [object Object].prepareHtmlparser (/Users/scott/node/lib/node/.npm/node.io/0.2.5-6/package/lib/node.io/dom.js:100:38)
    at [object Object].getHtml (/Users/scott/node/lib/node/.npm/node.io/0.2.5-6/package/lib/node.io/request.js:95:14)
    at [object Object].run (/Users/scott/Desktop/Projects/node/keywords.js:8:14)
    at EventEmitter.<anonymous> (/Users/scott/node/lib/node/.npm/node.io/0.2.5-6/package/lib/node.io/process_worker.js:254:28)
    at EventEmitter.emit (events.js:61:17)
    at Array.<anonymous> (/Users/scott/node/lib/node/.npm/node.io/0.2.5-6/package/lib/node.io/process_worker.js:106:24)
    at EventEmitter._tickCallback (node.js:126:26)
</pre></code>

**Comment by chriso** [comment]
Sorry, forgot to update all htmlparser references when I removed the submodule in [this commit](https://github.com/chriso/node.io/commit/5e211a8e8dac472d331ea91025dadc7cb650ee66).

[This commit](https://github.com/chriso/node.io/commit/9d9235a4b1bf71d59d4dc77a19936122a3b56aec) fixes the problem.

`sudo npm install node.io` and it'll be working.

**Comment by tazercat** [comment]
YEAAAHHHHH!!   Thank you!!
