### ISSUE TITLE
node-0.6 support

### ISSUE THREAD

**Issue by macrauder** [node-js-libs/node.io#65]
hi,
since a few day node-0.6 is as stable released it would be nice if node.io is also supporting it.
Currently i get a exception:

Error: No such module
    at Object.<anonymous> (./node_modules/node.io/lib/node.io/multi_node.js:6:26)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at Object.<anonymous> (./node_modules/node.io/lib/node.io/processor.js:10:13)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)

Thx

**Comment by chriso** [comment]
This is fixed in the latest `node.io v0.4.1` release
