### ISSUE TITLE
Module loading issues?

### ISSUE THREAD

**Issue by astrofinch** [node-js-libs/node.io#7]
Error message:

<pre>
john-laptop :: ~/tmp » node.io hello

node.js:63
    throw e;
    ^
Error: Cannot find module '/home/john/tmp/hello'
    at loadModule (node.js:275:15)
    at require (node.js:411:14)
    at [object Object].loadJob (/usr/local/lib/node/.npm/node.io/0.1.1-19/package/lib/node.io/processor.js:298:16)
    at Object.start (/usr/local/lib/node/.npm/node.io/0.1.1-19/package/lib/node.io/processor.js:152:30)
    at /usr/local/lib/node/.npm/node.io/0.1.1-19/package/lib/node.io/cli.js:124:19
    at Object.cli (/usr/local/lib/node/.npm/node.io/0.1.1-19/package/lib/node.io/cli.js:279:5)
    at Object.<anonymous> (/usr/local/lib/node/.npm/node.io/0.1.1-19/package/bin/node.io:3:20)
    at Module._compile (node.js:462:23)
    at Module._loadScriptSync (node.js:469:10)
    at Module.loadSync (node.js:338:12)
</pre>

However, this seems to work:

<pre>node.io hello.coffee</pre>

And oddly enough, this works (using double.coffee from the tutorial):<pre>node.io double</pre>

A related issue is that require statements don't seem to work properly.  Using double.coffee and quad.coffee from the tutorial,

<pre>

john-laptop :: ~/tmp » node.io quad.coffee                                  1 ↵
INFO: Compiling /home/john/tmp/quad.coffee

node.js:275
        throw new Error("Cannot find module '" + request + "'");
              ^
Error: Cannot find module './double'
    at loadModule (node.js:275:15)
    at require (node.js:411:14)
    at Object.<anonymous> (/home/john/tmp/quad_compiled.js:12:12)
    at Object.<anonymous> (/home/john/tmp/quad_compiled.js:25:4)
    at Module._compile (node.js:462:23)
    at Module._loadScriptSync (node.js:469:10)
    at Module.loadSync (node.js:338:12)
    at loadModule (node.js:283:14)
    at require (node.js:411:14)
    at [object Object].loadJob (/usr/local/lib/node/.npm/node.io/0.1.1-19/package/lib/node.io/processor.js:298:16)
</pre>

If I modify the original quad.coffee so it refers to double.coffee:

<pre>

john-laptop :: ~/tmp » node.io quad.coffee                                  1 ↵
INFO: Compiling /home/john/tmp/quad.coffee

/home/john/tmp/double.coffee:3
class Double extends nodeio.JobClass
      ^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (node.js:458:37)
    at Module._loadScriptSync (node.js:469:10)
    at Module.loadSync (node.js:338:12)
    at loadModule (node.js:283:14)
    at require (node.js:411:14)
    at Object.<anonymous> (/home/john/tmp/quad_compiled.js:12:12)
    at Object.<anonymous> (/home/john/tmp/quad_compiled.js:25:4)
    at Module._compile (node.js:462:23)
    at Module._loadScriptSync (node.js:469:10)
    at Module.loadSync (node.js:338:12)
</pre>

I even tried compiling double.coffee in to double.js and referring to it that way:

<pre>

john-laptop :: ~/tmp » node.io quad.coffee
john-laptop :: ~/tmp » node.io quad.coffee           
INFO: Compiling /home/john/tmp/quad.coffee

/home/john/tmp/quad_compiled.js:6
    ctor.prototype = parent.prototype;
                           ^
TypeError: Cannot read property 'prototype' of undefined
    at /home/john/tmp/quad_compiled.js:6:28
    at /home/john/tmp/quad_compiled.js:17:5
    at Object.<anonymous> (/home/john/tmp/quad_compiled.js:22:3)
    at Object.<anonymous> (/home/john/tmp/quad_compiled.js:25:4)
    at Module._compile (node.js:462:23)
    at Module._loadScriptSync (node.js:469:10)
    at Module.loadSync (node.js:338:12)
    at loadModule (node.js:283:14)
    at require (node.js:411:14)
    at [object Object].loadJob (/usr/local/lib/node/.npm/node.io/0.1.1-19/package/lib/node.io/processor.js:298:16)
</pre>

**Comment by chriso** [comment]
Hi John, thanks for the feedback. It seems that CoffeeScript inheritance is broken in a recent release - I'll look into it some more when I have time. As for `node.io hello` failing but `node.io hello.coffee` working.. have you got any other modules that may be conflicting with the call? When you run `node.io <module>` it looks for a .js file in the current dir, followed by a .coffee file, then it walks along the included paths (require.paths) looking for a match.

**Comment by astrofinch** [comment]
Do you think the CoffeeScript inheritance problem is most likely to be in CoffeeScript itself, in node.io, or in node.js?

hello.coffee is the only file in the directory that matches the hello.\* glob.

**Comment by chriso** [comment]
Hmm. Throw this in **hello.js** and run `$ node.io -s hello`

```
var nodeio = require('node.io');
exports.job = new nodeio.Job({
    input: false,
    run: function () {
        this.emit('Hello World!');
    }
});
```

Then add this to **hello.coffee** and run the same thing

```
nodeio = require 'node.io'
class Hello extends nodeio.JobClass
    input: false
    run: (num) -> @emit 'Hello World!'
@job = new Hello()
```

Both should output "Hello World!"

Now try running:

```
nodeio = require 'node.io'
class Double extends nodeio.JobClass
    input: [0,1,2]
    run: (num) -> @emit num * 2
class Quad extends Double
    run: (num) -> super num * 2
@job = new Quad()
```

It should output 0,4,8

Does this work? Also, what version of CoffeeScript and Node.JS are you using? `coffee -v && node -v`

Trying to `require` a CoffeeScript from within another .coffee file seems to fail - this definitely wasn't the case a little while ago - I haven't tested it with the latest version of CoffeeScript though..

**Comment by astrofinch** [comment]
Your hello.js produces this error:

<pre>
john-laptop :: ~/tmp » node.io -s hello.js
ERROR: This module expects input. Override the job's input method or call `node.io -i [INPUT] module`
</pre>


Both your coffeescript files work properly.  Here are my versions:

<pre>
john-laptop :: ~/tmp » coffee -v && node -v
CoffeeScript version 0.9.6
v0.2.4
</pre>


I'll look in to updating them presently.

**Comment by chriso** [comment]
Hi John, I think it's a 0.2.4 issue. I've only tested node.io with >= 0.2.5. Try upgrading to the latest stable and let me know how you go.. All of the tests are passing fine on 0.2.6

**Comment by chriso** [comment]
I'm closing this as resolved. Let me know if you still have issues

**Comment by astrofinch** [comment]
Sorry for not responding.  You guessed correctly that upgrading node solved my issue.  Thanks a lot!  :)

**Comment by chriso** [comment]
This has to do with the way npm/node resolves modules. You need to either modify your `NODE_PATH` to include the global install directory (probably `/usr/local/lib`) or you need to install `node.io` in the current working directory where you plan on running code that has `require('node.io')`.

Try running `npm install node.io` in the same directory that you're running the _hello.js_ example.
