### ISSUE TITLE
Error when running example queries

### ISSUE THREAD

**Issue by KyleAMathews** [node-js-libs/node.io#84]
I installed Node.io today and am getting the following error.

`$ node.io query "http://www.reddit.com" a.title`

`node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
TypeError: Object #<ClientRequest> has no method 'setTimeout'
    at Request.start (/usr/local/lib/node_modules/node.io/node_modules/request/main.js:458:14)
    at Request.end (/usr/local/lib/node_modules/node.io/node_modules/request/main.js:660:28)
    at Array.<anonymous> (/usr/local/lib/node_modules/node.io/node_modules/request/main.js:305:12)
    at EventEmitter._tickCallback (node.js:126:26)`

I'm running Node V. 4.12.

**Comment by chriso** [comment]
I can't replicate this. Can run `$ npm install node.io request` and try again?

**Comment by KyleAMathews** [comment]
I ran `npm install -g node.io request` and that worked! I think the problem was that request needed to be installed globally. Thanks!
