### ISSUE TITLE
version tracking

### ISSUE THREAD

**Issue by jmeyo** [node-js-libs/node.io#85]
Hi, 
Found hard to understand against which version of node and npm, node.io is linked. Maybe a page listing latest version of node.io and against whoch one they work would be a great idea.

node.io doesn't seems to work, whereas it was working yesterday, between i just reinstalled node and npm with the current stable version, I'm sure its a noobish error, but hard to say where I'm wrong :/

```
user@laptop:~$ node -v
v0.6.11
user@laptop:~$ npm -v
1.1.2

user@laptop:~$ sudo npm install -g node.io
npm http GET https://registry.npmjs.org/node.io
npm http 304 https://registry.npmjs.org/node.io
npm http GET https://registry.npmjs.org/htmlparser
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/jquery
npm http GET https://registry.npmjs.org/jsdom
npm http GET https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/jsdom
npm http 304 https://registry.npmjs.org/coffee-script
npm http 304 https://registry.npmjs.org/htmlparser
npm http 304 https://registry.npmjs.org/jquery
npm http GET https://registry.npmjs.org/cssom
npm http GET https://registry.npmjs.org/contextify
npm http 304 https://registry.npmjs.org/cssom
npm http 304 https://registry.npmjs.org/contextify

> contextify@0.1.1 preinstall /usr/local/lib/node_modules/node.io/node_modules/jsdom/node_modules/contextify
> node-waf clean || (exit 0); node-waf configure build

Nothing to clean (project not configured)
Setting srcdir to                        : /usr/local/lib/node_modules/node.io/node_modules/jsdom/node_modules/contextify 
Setting blddir to                        : /usr/local/lib/node_modules/node.io/node_modules/jsdom/node_modules/contextify/build 
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : ok /home/user/.node_libraries 
Checking for node prefix                 : ok /usr/local 
'configure' finished successfully (0.029s)
Waf: Entering directory `/usr/local/lib/node_modules/node.io/node_modules/jsdom/node_modules/contextify/build'
[1/2] cxx: src/contextify.cc -> build/Release/src/contextify_1.o
[2/2] cxx_link: build/Release/src/contextify_1.o -> build/Release/contextify.node
Waf: Leaving directory `/usr/local/lib/node_modules/node.io/node_modules/jsdom/node_modules/contextify/build'
'build' finished successfully (0.650s)
npm http GET https://registry.npmjs.org/bindings
npm http 500 https://registry.npmjs.org/bindings
/usr/local/bin/io -> /usr/local/lib/node_modules/node.io/bin/io
/usr/local/bin/node.io -> /usr/local/lib/node_modules/node.io/bin/node.io
/usr/local/bin/node.io-web -> /usr/local/lib/node_modules/node.io/bin/node.io-web
node.io@0.4.8-1 /usr/local/lib/node_modules/node.io 
├── jquery@1.6.3
├── request@2.9.152
├── htmlparser@1.7.4
├── coffee-script@1.2.0
└── jsdom@0.2.13


user@laptop:~$ node.io

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: require.paths is removed. Use node_modules folders, or the NODE_PATH environment variable instead.
    at Function.<anonymous> (module.js:378:11)
    at Object.<anonymous> (/home/user/bin/node.io@0.4.8-1:4:21)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:40)
```

**Comment by chriso** [comment]
The latest version of node.io works with all stable versions since `0.4.0`. Anything unstable (>= `0.7.0`) is unsupported. 

The `require.paths` call was removed from the library a while back. Try reinstalling the library with `$ npm install node.io`

**Comment by chriso** [comment]
Is this still an issue?
