### ISSUE TITLE
jsdom throws errors for external resources

### ISSUE THREAD

**Issue by discoverpost** [node-js-libs/node.io#91]
i need to call a function in an external script but jsdom is throwing errors that cause the scrape to fail. heres an example of those errors with reddit.com

https://gist.github.com/2348221

**Comment by chriso** [comment]
JSDOM errors are outside the scope of the library. You'll need to get in contact with the author of that library to fix the issue.

```
/Users/chris/test.js:24
    if (err) throw err;
                   ^
TypeError: needs a 'context' argument.
    at Object.getGlobal (/Users/chris/node_modules/node.io/node_modules/jsdom/lib/jsdom/browser/index.js:26:21)
    at Object.createWindow (/Users/chris/node_modules/node.io/node_modules/jsdom/lib/jsdom/browser/index.js:308:23)
    at Object.windowAugmentation (/Users/chris/node_modules/node.io/node_modules/jsdom/lib/jsdom/browser/index.js:63:24)
    at Object.parentWindow (/Users/chris/node_modules/node.io/node_modules/jsdom/lib/jsdom/browser/index.js:605:28)
    at Object.<anonymous> (/Users/chris/node_modules/node.io/node_modules/jsdom/lib/jsdom.js:81:15)
    at [object Object].parseHtml (/Users/chris/node_modules/node.io/lib/node.io/dom.js:59:101)
    at [object Object].<anonymous> (/Users/chris/node_modules/node.io/lib/node.io/request.js:109:18)
    at /Users/chris/node_modules/node.io/lib/node.io/request.js:217:25
    at /Users/chris/node_modules/node.io/lib/node.io/request.js:349:13
    at Request._callback (/Users/chris/node_modules/node.io/lib/node.io/request.js:359:13)
```
